cloud:
  aws:
    stack.auto: false
    region:
      static: ap-northeast-2

management:
  metrics:
    export:
      cloudwatch:
        namespace: sanghoonson-subway
        batch-size: 20
  endpoints:
    web:
      exposure:
        include: "*"
